CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" bigint NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Perfis" (
    "Id" bigint GENERATED ALWAYS AS IDENTITY,
    "IdUsuarioIdentity" bigint NOT NULL,
    CONSTRAINT "PK_Perfis" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Perfis_AspNetUsers_IdUsuarioIdentity" FOREIGN KEY ("IdUsuarioIdentity") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "Servicos" (
    "Id" bigint GENERATED ALWAYS AS IDENTITY,
    "IdPerfil" bigint NOT NULL,
    "Nome" varchar NOT NULL,
    "Descricao" varchar NOT NULL,
    "Valor" numeric(10,2) NOT NULL,
    "Inativo" boolean NOT NULL DEFAULT FALSE,
    "DataCriado" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Servicos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Servicos_Perfis_IdPerfil" FOREIGN KEY ("IdPerfil") REFERENCES "Perfis" ("Id")
);

CREATE TABLE "OrdemServicos" (
    "Id" bigint GENERATED ALWAYS AS IDENTITY,
    "IdServico" bigint NOT NULL,
    "IdPerfilPrestador" bigint NOT NULL,
    "IdPerfilSolicitante" bigint,
    "NomeSolicitante" varchar,
    "SolicitanteAnonimo" boolean NOT NULL,
    "Bairro" varchar NOT NULL,
    "Cep" varchar NOT NULL,
    "Cidade" varchar NOT NULL,
    "Numero" varchar,
    "Rua" varchar NOT NULL,
    "DataMarcado" timestamp with time zone NOT NULL,
    "DataFinalizado" timestamp with time zone,
    "DataCriacao" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_OrdemServicos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdemServicos_Perfis_IdPerfilPrestador" FOREIGN KEY ("IdPerfilPrestador") REFERENCES "Perfis" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrdemServicos_Perfis_IdPerfilSolicitante" FOREIGN KEY ("IdPerfilSolicitante") REFERENCES "Perfis" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrdemServicos_Servicos_IdServico" FOREIGN KEY ("IdServico") REFERENCES "Servicos" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_OrdemServicos_IdPerfilPrestador" ON "OrdemServicos" ("IdPerfilPrestador");

CREATE INDEX "IX_OrdemServicos_IdPerfilSolicitante" ON "OrdemServicos" ("IdPerfilSolicitante");

CREATE INDEX "IX_OrdemServicos_IdServico" ON "OrdemServicos" ("IdServico");

CREATE INDEX "IX_Perfis_IdUsuarioIdentity" ON "Perfis" ("IdUsuarioIdentity");

CREATE INDEX "IX_Servicos_IdPerfil" ON "Servicos" ("IdPerfil");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260427005438_InitialCreate', '9.0.14');

COMMIT;